# Generated by Django 5.0.2 on 2024-03-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='THUMBNAIL',
            field=models.ImageField(blank=True, upload_to='post', verbose_name='thumbnail img'),
        ),
    ]
